[package]
name = "snake2"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
rand = "0.8.4"
piston_window = "*"
rusttype = "0.9.2"
find_folder = "*"
